### ISSUE TITLE
Version of add-on is outdated 

### ISSUE THREAD

**Issue by tabriz79** [zhujisheng/hassio-addons#2]
How can I update it ??to the latest version of frp instead of version 0.32

**Comment by zhujisheng** [comment]
You can't.
If you want, you can modify `Dockerfile` and make the add-on image your self.

**Comment by tabriz79** [comment]
i looked for making addon and made a file on addon and i included docker config.json and run.sh and changed the versions on docker file also i commented out url and image on config.json file but when i hit install button on addon it showed this error 
The command '/bin/ash -o pipefail -c if [ "$BUILD_ARCH" = "armv7" ]; then wget https://github.com/fatedier/frp/releases/download/v0.37.0/frp_0.37.0_linux_arm.tar.gz && tar xvf frp_0.37.0_linux_arm.tar.gz && mv frp_0.37.0_linux_arm/frpc / && rm -rf frp_0.37.0_linux_arm.tar.gz frp_0.37.0_linux_arm ; elif [ "$BUILD_ARCH" = "armhf" ]; then wget https://github.com/fatedier/frp/releases/download/v0.37.0/frp_0.37.0_linux_arm.tar.gz && tar xvf frp_0.37.0_linux_arm.tar.gz && mv frp_0.37.0_linux_arm/frpc / && rm -rf frp_0.37.0_linux_arm.tar.gz frp_0.37.0_linux_arm ; elif [ "$BUILD_ARCH" = "aarch64" ]; then wget https://github.com/fatedier/frp/releases/download/v0.37.0/frp_0.37.0_linux_arm64.tar.gz && tar xvf frp_0.37.0_linux_arm64.tar.gz && mv frp_0.37.0_linux_arm64/frpc / && rm -rf frp_0.37.0_linux_arm64.tar.gz frp_0.37.0_linux_arm64 ; elif [ "$BUILD_ARCH" = "amd64" ]; then wget https://github.com/fatedier/frp/releases/download/v0.37.0/frp_0.37.0_linux_amd64.tar.gz && tar xvf frp_0.37.0_linux_amd64.tar.gz && mv frp_0.37.0_linux_amd64/frpc / && rm -rf frp_0.37.0_linux_amd64.tar.gz frp_0.37.0_linux_amd64 ; elif [ "$BUILD_ARCH" = "i386" ]; then wget https://github.com/fatedier/frp/releases/download/v0.37.0/frp_0.37.0_linux_386.tar.gz && tar xvf frp_0.37.0_linux_386.tar.gz && mv frp_0.37.0_linux_386/frpc / && rm -rf frp_0.37.0_linux_386.tar.gz frp_0.37.0_linux_386 ; else echo 'NOT VALID BUILD'; exit 1; fi' returned a non-zero code: 1

i run this on a raspberry pi4 
what is the problem ?

**Comment by zhujisheng** [comment]
you can run the script in an ssh add-on, and watch the error imformation.
